/* GRUPO 6
DAVI FAGUNDES FERREIRA DA SILVA		12544013
GUSTAVO SAMPAIO LIMA				12623992
PEDRO ROSSI SILVA RODRIGUES			11871775
THAÍS RIBEIRO LAURIANO 				12542518
THIERRY ARAÚJO DE SOUZA				12681094  
*/

CREATE TABLE PROVEDOR (
    CNPJ VARCHAR2(18) NOT NULL,
    NOME_FANTASIA VARCHAR2(255) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(255) NOT NULL,
    INICIO_CONTRATO DATE NOT NULL,
    DURACAO_CONTRATO NUMBER(2) NOT NULL,
    
    CONSTRAINT PK_PROVEDOR PRIMARY KEY(CNPJ),
    CONSTRAINT FILTRO_CNPJ CHECK(REGEXP_LIKE(CNPJ, '^\d{2}\.\d{3}\.\d{3}\/(0001|0002)-\d{2}$'))
);

CREATE TABLE ROTEADOR (
    MAC_ADDRESS VARCHAR2(17) NOT NULL,
    MODELO VARCHAR2(255),
    MARCA VARCHAR2(255),
    VELOCIDADE_MBPS INTEGER,
    ABRANGENCIA VARCHAR2(255) NOT NULL,
    TIPO_SINAL VARCHAR2(255) NOT NULL,
    
    CONSTRAINT PK_ROTEADOR PRIMARY KEY(MAC_ADDRESS),
    CONSTRAINT FILTRO_MAC_ADDRESS CHECK(REGEXP_LIKE(MAC_ADDRESS, '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')),
    CONSTRAINT CK_VELOCIDADE CHECK(VELOCIDADE_MBPS > 0)
);

CREATE TABLE ESTADO (
    NOME VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_ESTADO PRIMARY KEY(NOME)
);

CREATE TABLE COMUNIDADE (
    ID_COMUNIDADE INTEGER NOT NULL,
    ESTADO VARCHAR2(30) NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    NUM_HABITANTES INTEGER,
    REFERENCIA_LOC VARCHAR2(255),
    COORDENADAS_LOC VARCHAR2(255),
    ETNIA VARCHAR2(255),
    
    CONSTRAINT PK_COMUNIDADE PRIMARY KEY(ID_COMUNIDADE),
    CONSTRAINT FK_COMUNIDADE_ESTADO FOREIGN KEY(ESTADO) REFERENCES ESTADO(NOME),
    CONSTRAINT SK_COMUNIDADE UNIQUE (ESTADO, NOME),
    CONSTRAINT CK_NUM_HABITANTES CHECK(NUM_HABITANTES > 0)
);

CREATE TABLE FORNECIMENTO (
    ROTEADOR VARCHAR2(17) NOT NULL,
    PROVEDOR VARCHAR2(18) NOT NULL,
    CUSTO NUMBER(7, 2) NOT NULL,
    COMUNIDADE INTEGER NOT NULL,
    
    CONSTRAINT PK_FORNECIMENTO PRIMARY KEY(ROTEADOR),
    CONSTRAINT FK_FORNECIMENTO_ROTEADOR FOREIGN KEY(ROTEADOR) REFERENCES ROTEADOR(MAC_ADDRESS),
    CONSTRAINT FK_FORNECIMENTO_PROVEDOR FOREIGN KEY(PROVEDOR) REFERENCES PROVEDOR(CNPJ),
    CONSTRAINT FK_FORNECIMENTO_COMUNIDADE FOREIGN KEY(COMUNIDADE) REFERENCES COMUNIDADE(ID_COMUNIDADE),
    CONSTRAINT CK_CUSTO CHECK(CUSTO >= 0)
);


CREATE TABLE DIALETOS_COMUNIDADE (
    COMUNIDADE INTEGER NOT NULL,
    DIALETO VARCHAR2(255),
    
    CONSTRAINT PK_DIALETO_COMUNIDADE PRIMARY KEY(COMUNIDADE, DIALETO),
    CONSTRAINT FK_DIALETO_COMUNIDADE FOREIGN KEY(COMUNIDADE) REFERENCES COMUNIDADE(ID_COMUNIDADE)
);

CREATE TABLE HABITANTE (
    RG VARCHAR2(14) NOT NULL,
    COMUNIDADE INTEGER NOT NULL,
    NOME VARCHAR2(255),
    IDADE INTEGER,
    
    CONSTRAINT PK_HABITANTE PRIMARY KEY(RG),
    CONSTRAINT FK_HABITANTE FOREIGN KEY(COMUNIDADE) REFERENCES COMUNIDADE(ID_COMUNIDADE),
    CONSTRAINT CK_IDADE CHECK(IDADE >= 0)
);

CREATE TABLE CARGO (
    HABITANTE VARCHAR2(14) NOT NULL,
    CARGO VARCHAR2(255) NOT NULL,
    
    CONSTRAINT PK_CARGO PRIMARY KEY(HABITANTE, CARGO),
    CONSTRAINT FK_CARGO_HABITANTE FOREIGN KEY(HABITANTE) REFERENCES HABITANTE(RG)
);

CREATE TABLE CONTRATO (
    INTERLOCUTOR VARCHAR2(14) NOT NULL,
    ESTADO VARCHAR2(30) NOT NULL,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    COMUNIDADE INTEGER NOT NULL,

    CONSTRAINT PK_CONTRATO PRIMARY KEY(INTERLOCUTOR, ESTADO, INICIO),
    CONSTRAINT FK_CONTRATO_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADO(NOME),
    CONSTRAINT FK_CONTRATO_COMUNIDADE FOREIGN KEY (COMUNIDADE) REFERENCES COMUNIDADE(ID_COMUNIDADE),
    CONSTRAINT CK_DATAS_CONTRATO CHECK(INICIO < FIM)
);

CREATE TABLE DIRETOR_EMPRESA (
    RG VARCHAR2(14) NOT NULL,
    NOME VARCHAR2(255),
    IDADE INTEGER,
    SALARIO NUMBER(7,2),
    INICIO_CONTRATO DATE NOT NULL,
    FIM_CONTRATO DATE NOT NULL,

    CONSTRAINT PK_DIRETOR_EMPRESA PRIMARY KEY(RG),
    CONSTRAINT CK_DATAS_CONTRATO_DIRETOR CHECK(INICIO_CONTRATO < FIM_CONTRATO)
);

CREATE TABLE INTERLOCUTOR (
    RG VARCHAR2(14) NOT NULL,
    NOME VARCHAR2(255),
    IDADE INTEGER,
    SALARIO NUMBER(7,2),
    INICIO_CONTRATO DATE NOT NULL,
    FIM_CONTRATO DATE NOT NULL,
    SUPERVISOR VARCHAR2(14) NOT NULL,

    CONSTRAINT PK_INTERLOCUTOR PRIMARY KEY(RG),
    CONSTRAINT FK_INTERLOCUTOR FOREIGN KEY(SUPERVISOR) REFERENCES DIRETOR_EMPRESA(RG),
    CONSTRAINT CK_DATAS_CONTRATO_INTERLOC CHECK(INICIO_CONTRATO < FIM_CONTRATO)
);


CREATE TABLE DIALETO_INTERLOCUTOR (
    INTERLOCUTOR VARCHAR2(14) NOT NULL,
    DIALETO VARCHAR2(255) NOT NULL,
    NIVEL_FLUENCIA VARCHAR2(13),

    CONSTRAINT PK_DIALETOINTERLOCUTOR PRIMARY KEY(INTERLOCUTOR, DIALETO),
    CONSTRAINT FK_DIALETOINTERLOCUTOR FOREIGN KEY(INTERLOCUTOR) REFERENCES INTERLOCUTOR(RG)
);