/* GRUPO 6
DAVI FAGUNDES FERREIRA DA SILVA		        12544013
GUSTAVO SAMPAIO LIMA				12623992
PEDRO ROSSI SILVA RODRIGUES			11871775
THAÍS RIBEIRO LAURIANO 				12542518
THIERRY DE SOUZA ARAÚJO				12681094
*/

-- Selecionar as comunidades que possuem contrato ativo de fornecimento entre 12/2022 e 05/2023
SELECT F.COMUNIDADE as ID_COMUNIDADE, C.NOME, P.INICIO_CONTRATO, ADD_MONTHS(P.INICIO_CONTRATO, P.DURACAO_CONTRATO) as FIM_CONTRATO
FROM  FORNECIMENTO F
JOIN COMUNIDADE C ON F.COMUNIDADE = C.ID_COMUNIDADE
JOIN PROVEDOR P ON P.CNPJ = F.PROVEDOR
WHERE
   ADD_MONTHS(P.INICIO_CONTRATO, P.DURACAO_CONTRATO) >= TO_DATE('01/12/2022', 'DD/MM/YYYY') AND
    P.INICIO_CONTRATO <= TO_DATE('31/05/2023', 'DD/MM/YYYY');


-- Selecionar todas as comunidades que falam todas as línguas cadastradas em DialetosComunidade
SELECT C.NOME
FROM COMUNIDADE C
JOIN DIALETOS_COMUNIDADE DC ON C.ID_COMUNIDADE = DC.COMUNIDADE
GROUP BY C.NOME
HAVING COUNT(DISTINCT DC.DIALETO) = (SELECT COUNT(DISTINCT DIALETO) FROM DIALETOS_COMUNIDADE);


-- Localizar, em ordem decrescente de custo, os roteadores mais caros disponíveis para cada comunidade.
SELECT R.MAC_ADDRESS, R.MODELO, F.CUSTO, C.NOME
FROM ROTEADOR R
JOIN FORNECIMENTO F ON R.MAC_ADDRESS = F.ROTEADOR
JOIN COMUNIDADE C ON F.COMUNIDADE = C.ID_COMUNIDADE
WHERE (
    SELECT COUNT(*)
    FROM FORNECIMENTO F2
    WHERE F2.COMUNIDADE = F.COMUNIDADE AND F2.CUSTO >= F.CUSTO
) <= 1
ORDER BY F.CUSTO DESC;

--Selecionar a velocidade média dos roteadores por estado
SELECT C.ESTADO, AVG(R.VELOCIDADE_MBPS) AS VelocidadeMedia
FROM FORNECIMENTO F
JOIN ROTEADOR R ON F.ROTEADOR = R.MAC_ADDRESS
JOIN COMUNIDADE C ON F.COMUNIDADE = C.ID_COMUNIDADE
GROUP BY C.ESTADO
ORDER BY VelocidadeMedia DESC;

-- Obter as comunidades que possuem mais contratos ativos em cada estado:
SELECT C.ESTADO, C.NOME, C.ID_COMUNIDADE, C.NUM_HABITANTES, SUBQUERY.CONTRATOS
FROM COMUNIDADE C 
JOIN (
    SELECT COMUNIDADE, ESTADO, COUNT(*) AS CONTRATOS
    FROM CONTRATO WHERE INICIO <= TRUNC(SYSDATE) AND FIM >= TRUNC(SYSDATE)
    GROUP BY COMUNIDADE, ESTADO
        HAVING (ESTADO,COUNT(*)) IN (
            SELECT ESTADO, MAX(CONTRATOS)
            FROM (
                SELECT COMUNIDADE, ESTADO, COUNT(*) AS CONTRATOS
                FROM CONTRATO WHERE INICIO <= TRUNC(SYSDATE) AND FIM >= TRUNC(SYSDATE)
                GROUP BY COMUNIDADE, ESTADO
            ) TEMP
            GROUP BY ESTADO
        )
    ) SUBQUERY
ON (C.ID_COMUNIDADE = SUBQUERY.COMUNIDADE AND C.ESTADO = SUBQUERY.ESTADO)
ORDER BY ESTADO;